image: adoptopenjdk/openjdk11

stages:
  - build
  - deploy

build:
  stage: build
  allow_failure: false
  script:
    - ./gradlew clean bootWar
  artifacts:
    paths:
      - build/libs/gateway.war

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_KEY
    - aws configure set region ap-south-1
    - pip install awsebcli --upgrade --user
    - ~/.local/bin/eb use Gateway-env
    - ~/.local/bin/eb deploy
  dependencies:
    - build
  only:
    - master

# deploy:
#     stage: deploy
#     environment: production
#     # Pull docker image
#     image: 'mjsarfatti/gitlab-ci-pipeline-php-aws:latest'
#     # Setup AWS CLI to have proper credential keys
#     before_script:
#         - 'mkdir ~/.aws/'
#         - 'touch ~/.aws/credentials'
#         - 'printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials'
#     # Run deployment using EB CLI deploy on master branch
#     script:
#         - 'git checkout master'
#         - 'sudo pip install awsebcli'
#         - 'eb init --region ap-south-1 --platform java appname'
#         - 'eb use Gateway-env'
#         - 'eb deploy Gateway-env'
#     # Ensure to run deployment only on master branch
#     only:
#         - master
