logging:
  file:
    path: /var/log/tomcat/gateway.log
  level:
    root: info
    org.springframework.security: info
    
server:
  port: 9090

zuul:
  routes:
    admin:
      sensitive-headers:
      - Cookie,Set-Cookie
      url: http://internal-dev01-lb-38332093.ap-south-1.elb.amazonaws.com/administration
    customer:
      sensitive-headers:
      - Cookie,Set-Cookie
      url: http://internal-dev01-lb-38332093.ap-south-1.elb.amazonaws.com/rides
    bikes:
      sensitive-headers:
      - Cookie,Set-Cookie
      url: http://internal-dev-03lb-2125151772.ap-south-1.elb.amazonaws.com/bikes
    notificationclient:
      sensitive-headers:
      - Cookie,Set-Cookie
      url: http://internal-dev-03lb-2125151772.ap-south-1.elb.amazonaws.com/notificationclient
    notificationalerts:
      sensitive-headers:
      - Cookie,Set-Cookie
      url: http://internal-Dev-02LB-1005682274.ap-south-1.elb.amazonaws.com/notification-alerts
    docs:
      url: https://bud-e-dev-data.s3.ap-south-1.amazonaws.com
  sensitive-headers:
  ignored-headers:
  - Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ssl-hostname-validation-enabled: false   
spring:
  datasource:
    url: jdbc:mysql://bud-e-devdb.cluster-cg44srl3ob4p.ap-south-1.rds.amazonaws.com:3306/gateway
    username: gatewayuser
    password: Aimlytics$admin
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      initialization-fail-timeout: -1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

cors:
  filter:
    alloworigin: '*'
    allowmethods: POST,PUT,GET,OPTIONS,DELETE
    maxage: 3600
    allowheaders: '*'
    allowcredentials: true
#aws:
## secretkey: 7tqeRPAUCS1oAiSWrcSG27xsI0Qb0dLHmSBEXa5j
## accesskey: AKIAVO6HFBQH5NXZ5V44
##secretkey: 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
##accesskey: AKIAIBTECSIEW7YFF6RQ
aws:
  secretkey: 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
  accesskey: AKIAVO6HFBQH5NXZ5V44
  endpointurl: https://s3.ap-south-1.amazonaws.com
  bucket: bud-e-dev-data

gatewayUrl: https://testapi.budd-e.co.in

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    urls[0]:
      url: ${gatewayUrl}/admin/v3/api-docs
      name: admin
    urls[1]:
      url: ${gatewayUrl}/customer/v3/api-docs
      name: customer
    urls[2]:
      url: ${gatewayUrl}/bikes/v3/api-docs
      name: bikes
    urls[3]:
      url: ${gatewayUrl}/notificationclient/v3/api-docs
      name: notification-client
    urls[4]:
      url: ${gatewayUrl}/notificationalerts/v3/api-docs
      name: notification-alerts
    urls[5]:
      url: ${gatewayUrl}/v3/api-docs
      name: gateway
    oauth:
      clientId: client
      clientSecret: clientpassword
