logging:
  file:
    path: /home/ec2-user/logs/gateway.log
  level:
    root: info
    org.springframework.security: debug
    #org.apache.http: trace

server:
  port: 9090

zuul:
  routes:
    admin:
      sensitive-headers:
        - Cookie,Set-Cookie
      url: https://testaadminride.bud-e.co.in/administration
    customer:
      sensitive-headers:
        - Cookie,Set-Cookie
      url: https://testaadminride.bud-e.co.in/rides
    bikes:
      sensitive-headers:
        - Cookie,Set-Cookie
      url: https://testeiot.bud-e.co.in/bikes
    docs:
      url: https://ev-dev-data.s3.ap-south-1.amazonaws.com
    v3:
      url: forward:/v3   # forward to locally handle the request
  sensitive-headers:
  ignored-headers:
    - Access-Control-Allow-Credentials, Access-Control-Allow-Origin
spring:
  datasource:
    url: jdbc:mysql://seef-gateway-instance-1.csc5evvkzpgn.ap-south-1.rds.amazonaws.com:3306/gateway
    username: gatewayuser
    password: Aimlytics$admin
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      initialization-fail-timeout: -1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
cors:
  filter:
    alloworigin: '*'
    allowmethods: POST,PUT,GET,OPTIONS,DELETE
    maxage: 3600
    allowheaders: X-Requested-With,X-Auth-Token,Content-Type,X-SCOPE-ID,Authorization,X-ORG-ID
    allowcredentials: true

aws:
  secretkey: tU0J7mcy1JWCOtf9CP26Qg+UxKKzfIRFj0mi/Peh
  accesskey: AKIAIBTECSIEW7YFF6RQ
  endpointurl: https://s3.ap-south-1.amazonaws.com
  bucket: ev-dev-data

  #swagger config need to be removed in production
gatewayUrl: https://testapi.bud-e.co.in

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    urls[0]:
      url: ${gatewayUrl}/admin/v3/api-docs
      name: admin
    urls[1]:
      url: ${gatewayUrl}/customer/v3/api-docs
      name: customer
    urls[2]:
      url: ${gatewayUrl}/bikes/v3/api-docs
      name: bikes
    urls[3]:
      url: ${gatewayUrl}/v3/api-docs
      name: gateway
    oauth:
      clientId: client
      clientSecret: clientpassword
